stages: 
  - security

security:
  stage: security
  trigger:
    include:
      - local: 'pipelines.yml'
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"

  variables:
    SEC_CODE_CLONE: ${SEC_CODE_CLONE}
    DOJO_PROJECT_TYPE: ${DOJO_PROJECT_TYPE}
    DOJO_PROJECT_DESCRIPTION: ${DOJO_PROJECT_DESCRIPTION}
    DOJO_PROJECT_NAME: ${DOJO_PROJECT_NAME}
    DOJO_REPO_URL: ${DOJO_REPO_URL}
    REPO_URL: ${REPO_URL}

    # Secrets settings
    SEC_SECRETS_SCAN_ENABLE: ${SEC_SECRETS_SCAN_ENABLE}

    # SAST settings
    SEC_GREP: ${SEC_GREP}
    SEC_SEMGREP_CONFIG: ${SEC_SEMGREP_CONFIG:-'p/ci'}
    SEC_SEMGREP_EXCLUDE: ${SEC_SEMGREP_EXCLUDE:-'/tests'}
    SEC_PYTHON: ${SEC_PYTHON:-false}
    SEC_RUBY: ${SEC_RUBY:-false}
    SEC_PHP: ${SEC_PHP:-false}
    SEC_PHPCS_STANDARD: ${SEC_PHPCS_STANDARD:-'/tmp/vendor/pheromone/phpcs-security-audit/example_base_ruleset.xml'}
    SEC_JS: ${SEC_JS:-false}
    SEC_ESLINT_CONFIG_PATH: ${SEC_ESLINT_CONFIG_PATH:-'/eslint/eslintrc-light.js'}
    SEC_GOLANG: ${SEC_GOLANG:-false}
    SEC_GOSEC_MINIMUM_SEVERITY: ${SEC_GOSEC_MINIMUM_SEVERITY:-'low'}
    SEC_GOSEC_EXCLUDE: ${SEC_GOSEC_EXCLUDE:-'G102,G103,G104,G307'}
    
    # Dependency check settings
    SEC_IMAGE_SCAN_ENABLE: ${SEC_IMAGE_SCAN_ENABLE}
    SEC_IMAGE_TO_SCAN_NAME: ${SEC_IMAGE_TO_SCAN_NAME}
    SEC_IMAGE_TO_SCAN_TAG: ${SEC_IMAGE_TO_SCAN_TAG}
    SEC_IMAGE_REGISTRY_URL: ${SEC_IMAGE_REGISTRY_URL}
    SEC_IMAGE_REGISTRY_USER: ${SEC_IMAGE_REGISTRY_USER}
    SEC_IMAGE_REGISTRY_PASS: ${SEC_IMAGE_REGISTRY_PASS}
    SEC_TRIVY_MINIMUM_SEVERITY: ${SEC_TRIVY_MINIMUM_SEVERITY:-'HIGH,CRITICAL'}
    SEC_CLEANUP_ENABLE: ${SEC_CLEANUP_ENABLE:-false} # only for defectdojo

    # DAST settings
    SEC_DAST_ENABLE: ${SEC_DAST_ENABLE}
    SEC_DAST_URL_TO_SCAN: ${SEC_DAST_URL_TO_SCAN}
    SEC_ARACHNI_ADDITIONAL_FLAGS: ''
    # for this flag you need to set up your qa tests in common/dast.yml
    SEC_ZAP_AUTOTESTS_GIT_REPO_URL: ${SEC_ZAP_AUTOTESTS_GIT_REPO_URL}
    QA_AUTOTESTS_NAME: ${QA_AUTOTESTS_NAME}

    # Mobile settings
    SEC_MOBILE_ENABLE: ${SEC_MOBILE_ENABLE}
    SEC_MOBILE_APK_PATH: ${SEC_MOBILE_APK_PATH}
    SEC_MOBILE_SCAN_TYPE: ${SEC_MOBILE_SCAN_TYPE:-apk} # "apk|ios"
    SEC_CHECKKARLMARX_DOMAIN: ${SEC_CHECKKARLMARX_DOMAIN}
    SEC_CHECKKARLMARX_QA_TAGS: ${SEC_CHECKKARLMARX_QA_TAGS}
    SEC_CHECKKARLMARX_PACKAGES: ${SEC_CHECKKARLMARX_PACKAGES}

    # Infrastructure scanners
    SEC_INFRA_ENABLE: ${SEC_INFRA_ENABLE}
    SEC_INFRA_DOMAIN: ${SEC_INFRA_DOMAIN}
    SEC_NUCLEI_TEMPLATES: ${SEC_NUCLEI_TEMPLATES:-'-t exposures -t exposed-panels'}