stages: 
  # after build stage
  - security

security:
  stage: security
  allow_failure: true
  trigger:
    include:
    # Path to the shared repo
      - project: 'whitespots-public/pipelines'
        # a proper branch name
        ref: 'main'
        file: 'pipelines.yml'
  variables:

    # DAST settings
    SEC_INFRA_ENABLE: "true"
    SEC_INFRA_DOMAIN: "example.com"
    SEC_DAST_URL_TO_SCAN: "https://example.com"

